import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";

const seogefont = localFont({
  src: "./fonts/segoeuithis.ttf",
});

export const metadata: Metadata = {
  title: "Starline ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${seogefont.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
